### ISSUE TITLE
Save game structure documentation?

### ISSUE THREAD

**Issue by StefanOltmann** [RoboPhred/oni-save-parser#21]
Is there any documentation you used to understand how the save file is structured?

**Comment by SunsetFi** [comment]
Nope, this was implemented by reverse engineering the game code.

I attempted to build this library in a way that would be more easy to understand, so in a way this might work as its own source of documentation, provided you can parse the syntax.

All of the save reading and writing are in `parser.ts` files in the various folders of the [save structure folder](https://github.com/RoboPhred/oni-save-parser/tree/master/src/save-structure), with the main entrypoint being at the [top level parser file](https://github.com/RoboPhred/oni-save-parser/blob/master/src/save-structure/parser.ts#L69)

These are javascript generator functions, which are basically functions that can suspend their execution to pass a request up to whoever called them, and receive a response to that request before resuming execution.  This is done by the `yield` keyword.  There are two forms of this:

Basic requests to read data from the file stream look like this:
```ts
const buildVersion = yield readUInt32();
```

The parse process can also be delegated to an entire subroutine, done with the star symbol:
```ts
const header: SaveGameHeader = yield* parseHeader();
```

As for the read instructions, the functions seen after the yield don't actually do any work, but instead return an object describing the data type to be read.  The actual reading is performed by a DataReader, such as the [ArrayReader](https://github.com/RoboPhred/oni-save-parser/blob/master/src/binary-serializer/data-reader/array-reader.ts).  You can review this code to see the details of how the values are processed (eg: little endian, 'klei string').

You should be able to follow the logical flow of the top level parser to see what data is read in at each step.  The whole process should be mostly straightforward once you get the hang of understanding how the parser functions operate.

Some interesting quirks to note:
- After the header, the save file contents are compressed.  This library handles that transparently by swapping out the regular ArrayReader with one that decompresses the data.  The logic that triggers that is [here](https://github.com/RoboPhred/oni-save-parser/blob/master/src/save-structure/parser.ts#L87).
- The game stores dynamic serialization formats into the save files, probably to help with backwards compatibility.  This takes the form of a list of C# class field and property names and a high level description of the types (which can be recursive).  These are deserialized from the save, then their data is used to deserialize objects that target that type.
  - These type templates are deserialized before the rest of the data [here](https://github.com/RoboPhred/oni-save-parser/blob/master/src/save-structure/parser.ts#L80).
  - The templates define type codes and associated data which then must be interpreted correctly when deserializing the requested type.  The logic to do this can be quite complex due to their recursive nature.  This is implemented [here](https://github.com/RoboPhred/oni-save-parser/blob/master/src/save-structure/type-templates/type-data-parser.ts#L143)
  - Type templates are used several times through the save, but their most significant use is in deserializing the game object behaviors.  You can see that being invoked [here](https://github.com/RoboPhred/oni-save-parser/blob/master/src/save-structure/game-objects/game-object-behavior/parser.ts#L85)

**Comment by RoboPhred** [comment]
Nope, this was implemented by reverse engineering the game code.

I attempted to build this library in a way that would be more easy to understand, so in a way this might work as its own source of documentation, provided you can parse the syntax.

All of the save reading and writing are in `parser.ts` files in the various folders of the [save structure folder](https://github.com/RoboPhred/oni-save-parser/tree/master/src/save-structure), with the main entrypoint being at the [top level parser file](https://github.com/RoboPhred/oni-save-parser/blob/master/src/save-structure/parser.ts#L69)

These are javascript generator functions, which are basically functions that can suspend their execution to pass a request up to whoever called them, and receive a response to that request before resuming execution.  This is done by the `yield` keyword.  There are two forms of this:

Basic requests to read data from the file stream look like this:
```ts
const buildVersion = yield readUInt32();
```

The parse process can also be delegated to an entire subroutine, done with the star symbol:
```ts
const header: SaveGameHeader = yield* parseHeader();
```

As for the read instructions, the functions seen after the yield don't actually do any work, but instead return an object describing the data type to be read.  The actual reading is performed by a DataReader, such as the [ArrayReader](https://github.com/RoboPhred/oni-save-parser/blob/master/src/binary-serializer/data-reader/array-reader.ts).  You can review this code to see the details of how the values are processed (eg: little endian, 'klei string').

You should be able to follow the logical flow of the top level parser to see what data is read in at each step.  The whole process should be mostly straightforward once you get the hang of understanding how the parser functions operate.

Some interesting quirks to note:
- After the header, the save file contents are compressed.  This library handles that transparently by swapping out the regular ArrayReader with one that decompresses the data.  The logic that triggers that is [here](https://github.com/RoboPhred/oni-save-parser/blob/master/src/save-structure/parser.ts#L87).
- The game stores dynamic serialization formats into the save files, probably to help with backwards compatibility.  This takes the form of a list of C# class field and property names and a high level description of the types (which can be recursive).  These are deserialized from the save, then their data is used to deserialize objects that target that type.
  - These type templates are deserialized before the rest of the data [here](https://github.com/RoboPhred/oni-save-parser/blob/master/src/save-structure/parser.ts#L80).
  - The templates define type codes and associated data which then must be interpreted correctly when deserializing the requested type.  The logic to do this can be quite complex due to their recursive nature.  This is implemented [here](https://github.com/RoboPhred/oni-save-parser/blob/master/src/save-structure/type-templates/type-data-parser.ts#L143)
  - Type templates are used several times through the save, but their most significant use is in deserializing the game object behaviors.  You can see that being invoked [here](https://github.com/RoboPhred/oni-save-parser/blob/master/src/save-structure/game-objects/game-object-behavior/parser.ts#L85)

**Comment by StefanOltmann** [comment]
Understood, thank you.
